- # Gmod-ACF-ACE-2A46-Cannon
- 2A46 Cannon for you use in your ACF/ACE builds!
- This is not E2, its Prop2 Mesh.
- need= Sprops and Prop2 Mesh.
- when you download, go to Gmod folder= Windows (C:)/ Program Files(x86)/ Steam/ SteamApps/ Common/ Garry's mod/ garrysmod/ Data/ AdvDupe2.
- open the ZIP you downloaded, take the 2A46 folder and put in AdvDupe2.
- Have fun!
